name: Update sing-box
on:
workflow_dispatch:
schedule:
# 每天北京时间 04:30（UTC 20:30）
- cron: "30 20 * * *"

push:
branches:
- main
paths-ignore:
- "README.md"
- ".github/workflows/delete-old-workflows.yml"
- ".github/workflows/update-adguardhome.yml"
- ".github/workflows/update-dashboard.yml"
- ".github/workflows/update-mihomo.yml"

permissions:
contents: write

jobs:
ref1nd_stable_version:
runs-on: ubuntu-latest
outputs:
ref1nd_stable_version: ${{ steps.version.outputs.ref1nd_stable_version }}
ref1nd_stable_time: ${{ steps.version.outputs.ref1nd_stable_time }}
ref1nd_stable_skip_update: ${{ steps.compare.outputs.skip_update }}
steps:
- name: Get `sing-box reF1nd-Stable` version
id: version
run: |
while true; do
for i in {1..5}; do
tags=$(curl -sSL "https://api.github.com/repos/reF1nd/sing-box/tags?per_page=100&page=$i")
ref1nd_stable_version=$(echo "${tags}" | jq -r '.[].name' | grep -Po '^v?\K[0-9]+.[0-9]+.[0-9]+-reF1nd.*' | head -n 1)
if [[ -n "${ref1nd_stable_version}" && "${ref1nd_stable_version}" != "null" ]]; then
echo "在第 $i 页成功获取到 reF1nd-Stable 版本号"
ref1nd_stable_time=$(curl -sSL "https://api.github.com/repos/reF1nd/sing-box/commits/v${ref1nd_stable_version}" | jq -r '.commit.committer.date' | xargs -I {} date -d '{} +8 hours' '+%Y-%m-%d')
echo "ref1nd_stable_version=${ref1nd_stable_version}" >> "${GITHUB_OUTPUT}"
echo "ref1nd_stable_time=${ref1nd_stable_time}" >> "${GITHUB_OUTPUT}"
exit 0
fi
echo "在第 $i 页未获取到 reF1nd-Stable 版本号，将在 5 秒后重试在第 $((i+1)) 页获取..."
sleep 5
done
echo "未获取到 reF1nd-Stable 版本号，将在 10 秒后重试..."
sleep 10
done

```
  - name: Compare `sing-box reF1nd-Stable` versions with current release
    id: compare
    run: |
      current_body=$(curl -sSL "https://api.github.com/repos/${{ github.repository }}/releases/tags/sing-box" | jq -r '.body // ""')
      arch="sing-box reF1nd-Stable|${{ steps.version.outputs.ref1nd_stable_version }}|${{ steps.version.outputs.ref1nd_stable_time }}"
      IFS="|" read -r name version time <<< "$arch"
      if echo "${current_body}" | grep -q "${name}.*${version}.*${time}"; then
        echo "当前 ${name} 版本已是最新版本 v${version}，无需更新"
        skip_update=true
      else
        echo "当前 ${name} 版本较低，需要更新最新版本至 v${version}"
        skip_update=false
      fi
      echo "skip_update=${skip_update}" >> "${GITHUB_OUTPUT}"
```

ref1nd_stable_cross:
runs-on: ubuntu-latest
if: ${{ needs.ref1nd_stable_version.outputs.ref1nd_stable_skip_update != 'true' }}
strategy:
matrix:
include:
# Linux
- { name: linux-amd64-v1, goos: linux, goarch: amd64, goamd64: v1, variant: purego }
- { name: linux-amd64-v3, goos: linux, goarch: amd64, goamd64: v3, variant: purego }
- { name: linux-armv5, goos: linux, goarch: arm, goarm: 5 }
- { name: linux-armv6, goos: linux, goarch: arm, goarm: 6 }
- { name: linux-armv7, goos: linux, goarch: arm, goarm: 7 }
- { name: linux-arm64, goos: linux, goarch: arm64, variant: purego }
- { name: linux-mips-softfloat, goos: linux, goarch: mips, gomips: softfloat }
- { name: linux-mipsle-softfloat, goos: linux, goarch: mipsle, gomips: softfloat }
- { name: linux-mipsle-hardfloat, goos: linux, goarch: mipsle, gomips: hardfloat }

```
      # Windows
      - { name: windows-amd64-v1, goos: windows, goarch: amd64, goamd64: v1 }
      - { name: windows-amd64-v3, goos: windows, goarch: amd64, goamd64: v3 }
      - { name: windows-arm64, goos: windows, goarch: arm64 }

  fail-fast: false

needs:
  - ref1nd_stable_version

env:
  GOOS: ${{ matrix.goos }}
  GOARCH: ${{ matrix.goarch }}
  GOAMD64: ${{ matrix.goamd64 }}
  GOARM: ${{ matrix.goarm }}
  GOMIPS: ${{ matrix.gomips }}
  CGO_ENABLED: 0
  ref1nd_stable_VERSION: ${{ needs.ref1nd_stable_version.outputs.ref1nd_stable_version }}

steps:
  - name: Checkout `reF1nd/sing-box`
    uses: actions/checkout@v7
    with:
      repository: reF1nd/sing-box
      ref: reF1nd-stable

  - name: Get `Go` version
    id: go
    run: |
      echo "go_version=$(curl -sSL https://raw.githubusercontent.com/reF1nd/sing-box/reF1nd-stable/.github/workflows/build.yml | grep 'go-version:' | head -n 1 | awk '{print $2}')" >> "${GITHUB_OUTPUT}"

  - name: Setup `Go`
    uses: actions/setup-go@v7
    with:
      go-version: ${{ steps.go.outputs.go_version }}

  - name: Set `build tags`
    id: tags
    run: |
      if [[ "${{ matrix.goos }}" == "linux" ]]; then
        echo "build_tags=with_quic,with_utls,with_clash_api" >> "${GITHUB_OUTPUT}"
      elif [[ "${{ matrix.goos }}" == "windows" ]]; then
        echo "build_tags=with_gvisor,with_quic,with_utls,with_clash_api,with_tailscale" >> "${GITHUB_OUTPUT}"
      fi

  - name: Build `sing-box reF1nd-Stable` core
    run: go build -v -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${ref1nd_stable_VERSION}' -s -w -buildid=" -tags "${{ steps.tags.outputs.build_tags }}" ./cmd/sing-box

  - name: Upload files to workspace
    uses: actions/upload-artifact@v7
    with:
      name: sing-box-ref1nd-stable-${{ matrix.name }}
      path: sing-box*
```

ref1nd_testing_version:
runs-on: ubuntu-latest
outputs:
ref1nd_testing_version: ${{ steps.version.outputs.ref1nd_testing_version }}
ref1nd_testing_time: ${{ steps.version.outputs.ref1nd_testing_time }}
ref1nd_testing_skip_update: ${{ steps.compare.outputs.skip_update }}
steps:
- name: Get `sing-box reF1nd-Testing` version
id: version
run: |
while true; do
tags=$(curl -sSL https://api.github.com/repos/reF1nd/sing-box/tags)
ref1nd_testing_version=$(echo "${tags}" | jq -r '.[].name' | grep -Po '^v\K.*(alpha|beta|rc).*-reF1nd.*' | head -n 1)
if [[ -n "${ref1nd_testing_version}" && "${ref1nd_testing_version}" != "null" ]]; then
ref1nd_testing_time=$(curl -sSL "https://api.github.com/repos/reF1nd/sing-box/commits/v${ref1nd_testing_version}" | jq -r '.commit.committer.date' | xargs -I {} date -d '{} +8 hours' '+%Y-%m-%d')
echo "ref1nd_testing_version=${ref1nd_testing_version}" >> "${GITHUB_OUTPUT}"
echo "ref1nd_testing_time=${ref1nd_testing_time}" >> "${GITHUB_OUTPUT}"
break
fi
echo "未获取到 reF1nd-Testing 版本号，将在 10 秒后重试..."
sleep 10
done

```
  - name: Compare `sing-box reF1nd-Testing` versions with current release
    id: compare
    run: |
      current_body=$(curl -sSL "https://api.github.com/repos/${{ github.repository }}/releases/tags/sing-box" | jq -r '.body // ""')
      arch="sing-box reF1nd-Testing|${{ steps.version.outputs.ref1nd_testing_version }}|${{ steps.version.outputs.ref1nd_testing_time }}"
      IFS="|" read -r name version time <<< "$arch"
      if echo "${current_body}" | grep -q "${name}.*${version}.*${time}"; then
        echo "当前 ${name} 版本已是最新版本 v${version}，无需更新"
        skip_update=true
      else
        echo "当前 ${name} 版本较低，需要更新最新版本至 v${version}"
        skip_update=false
      fi
      echo "skip_update=${skip_update}" >> "${GITHUB_OUTPUT}"
```

ref1nd_testing_cross:
runs-on: ubuntu-latest
if: ${{ needs.ref1nd_testing_version.outputs.ref1nd_testing_skip_update != 'true' }}
strategy:
matrix:
include:
# Linux
- { name: linux-amd64-v1, goos: linux, goarch: amd64, goamd64: v1, variant: purego }
- { name: linux-amd64-v3, goos: linux, goarch: amd64, goamd64: v3, variant: purego }
- { name: linux-armv5, goos: linux, goarch: arm, goarm: 5 }
- { name: linux-armv6, goos: linux, goarch: arm, goarm: 6 }
- { name: linux-armv7, goos: linux, goarch: arm, goarm: 7 }
- { name: linux-arm64, goos: linux, goarch: arm64, variant: purego }
- { name: linux-mips-softfloat, goos: linux, goarch: mips, gomips: softfloat }
- { name: linux-mipsle-softfloat, goos: linux, goarch: mipsle, gomips: softfloat }
- { name: linux-mipsle-hardfloat, goos: linux, goarch: mipsle, gomips: hardfloat }

```
      # Windows
      - { name: windows-amd64-v1, goos: windows, goarch: amd64, goamd64: v1 }
      - { name: windows-amd64-v3, goos: windows, goarch: amd64, goamd64: v3 }
      - { name: windows-arm64, goos: windows, goarch: arm64 }

  fail-fast: false

needs:
  - ref1nd_testing_version

env:
  GOOS: ${{ matrix.goos }}
  GOARCH: ${{ matrix.goarch }}
  GOAMD64: ${{ matrix.goamd64 }}
  GOARM: ${{ matrix.goarm }}
  GOMIPS: ${{ matrix.gomips }}
  CGO_ENABLED: 0
  ref1nd_testing_VERSION: ${{ needs.ref1nd_testing_version.outputs.ref1nd_testing_version }}

steps:
  - name: Checkout `reF1nd/sing-box`
    uses: actions/checkout@v7
    with:
      repository: reF1nd/sing-box
      ref: reF1nd-testing

  - name: Get `Go` version
    id: go
    run: |
      echo "go_version=$(curl -sSL https://raw.githubusercontent.com/reF1nd/sing-box/reF1nd-testing/.github/workflows/build.yml | grep 'go-version:' | head -n 1 | awk '{print $2}')" >> "${GITHUB_OUTPUT}"

  - name: Setup `Go`
    uses: actions/setup-go@v7
    with:
      go-version: ${{ steps.go.outputs.go_version }}

  - name: Set `build tags`
    id: tags
    run: |
      if [[ "${{ matrix.goos }}" == "linux" ]]; then
        echo "build_tags=with_quic,with_utls,with_clash_api" >> "${GITHUB_OUTPUT}"
      elif [[ "${{ matrix.goos }}" == "windows" ]]; then
        echo "build_tags=with_gvisor,with_quic,with_utls,with_clash_api,with_tailscale" >> "${GITHUB_OUTPUT}"
      fi

  - name: Build `sing-box reF1nd-Testing` core
    run: go build -v -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${ref1nd_testing_VERSION}' -s -w -buildid=" -tags "${{ steps.tags.outputs.build_tags }}" ./cmd/sing-box

  - name: Upload files to workspace
    uses: actions/upload-artifact@v6
    with:
      name: sing-box-ref1nd-testing-${{ matrix.name }}
      path: sing-box*
```

singbox_stable_version:
runs-on: ubuntu-latest
outputs:
singbox_stable_version: ${{ steps.version.outputs.singbox_stable_version }}
singbox_stable_time: ${{ steps.version.outputs.singbox_stable_time }}
singbox_stable_skip_update: ${{ steps.compare.outputs.skip_update }}
steps:
- name: Get `sing-box Stable` version
id: version
run: |
while true; do
latest=$(curl -sSL https://api.github.com/repos/SagerNet/sing-box/releases/latest)
singbox_stable_version=$(echo "${latest}" | jq -r '.tag_name' | sed 's/^v//')
if [[ -n "${singbox_stable_version}" && "${singbox_stable_version}" != "null" ]]; then
singbox_stable_time=$(echo "${latest}" | jq -r '.published_at // .created_at' | xargs -I {} date -d '{} +8 hours' '+%Y-%m-%d')
echo "singbox_stable_version=${singbox_stable_version}" >> "${GITHUB_OUTPUT}"
echo "singbox_stable_time=${singbox_stable_time}" >> "${GITHUB_OUTPUT}"
break
fi
echo "未获取到 sing-box Stable 版本号，将在 10 秒后重试..."
sleep 10
done

```
  - name: Compare `sing-box Stable` versions with current release
    id: compare
    run: |
      current_body=$(curl -sSL "https://api.github.com/repos/${{ github.repository }}/releases/tags/sing-box" | jq -r '.body // ""')
      arch="sing-box Stable|${{ steps.version.outputs.singbox_stable_version }}|${{ steps.version.outputs.singbox_stable_time }}"
      IFS="|" read -r name version time <<< "$arch"
      if echo "${current_body}" | grep -q "${name}.*${version}.*${time}"; then
        echo "当前 ${name} 版本已是最新版本 v${version}，无需更新"
        skip_update=true
      else
        echo "当前 ${name} 版本较低，需要更新最新版本至 v${version}"
        skip_update=false
      fi
      echo "skip_update=${skip_update}" >> "${GITHUB_OUTPUT}"
```

singbox_stable_cross:
runs-on: ubuntu-latest
if: ${{ needs.singbox_stable_version.outputs.singbox_stable_skip_update != 'true' }}
strategy:
matrix:
include:
# Linux
- { name: linux-amd64-v1, goos: linux, goarch: amd64, goamd64: v1, variant: purego }
- { name: linux-amd64-v3, goos: linux, goarch: amd64, goamd64: v3, variant: purego }
- { name: linux-armv5, goos: linux, goarch: arm, goarm: 5 }
- { name: linux-armv6, goos: linux, goarch: arm, goarm: 6 }
- { name: linux-armv7, goos: linux, goarch: arm, goarm: 7 }
- { name: linux-arm64, goos: linux, goarch: arm64, variant: purego }
- { name: linux-mips-softfloat, goos: linux, goarch: mips, gomips: softfloat }
- { name: linux-mipsle-softfloat, goos: linux, goarch: mipsle, gomips: softfloat }
- { name: linux-mipsle-hardfloat, goos: linux, goarch: mipsle, gomips: hardfloat }

```
      # Windows
      - { name: windows-amd64-v1, goos: windows, goarch: amd64, goamd64: v1 }
      - { name: windows-amd64-v3, goos: windows, goarch: amd64, goamd64: v3 }
      - { name: windows-arm64, goos: windows, goarch: arm64 }

  fail-fast: false

needs:
  - singbox_stable_version

env:
  GOOS: ${{ matrix.goos }}
  GOARCH: ${{ matrix.goarch }}
  GOAMD64: ${{ matrix.goamd64 }}
  GOARM: ${{ matrix.goarm }}
  GOMIPS: ${{ matrix.gomips }}
  CGO_ENABLED: 0
  singbox_stable_VERSION: ${{ needs.singbox_stable_version.outputs.singbox_stable_version }}

steps:
  - name: Checkout `SagerNet/sing-box`
    uses: actions/checkout@v7
    with:
      repository: SagerNet/sing-box
      ref: stable

  - name: Get `Go` version
    id: go
    run: |
      echo "go_version=$(curl -sSL https://raw.githubusercontent.com/SagerNet/sing-box/stable/.github/workflows/build.yml | grep 'go-version:' | head -n 1 | awk '{print $2}')" >> "${GITHUB_OUTPUT}"

  - name: Setup `Go`
    uses: actions/setup-go@v7
    with:
      go-version: ${{ steps.go.outputs.go_version }}

  - name: Set `build tags`
    id: tags
    run: |
      if [[ "${{ matrix.goos }}" == "linux" ]]; then
        echo "build_tags=with_quic,with_utls,with_clash_api" >> "${GITHUB_OUTPUT}"
      elif [[ "${{ matrix.goos }}" == "windows" ]]; then
        echo "build_tags=with_gvisor,with_quic,with_utls,with_clash_api,with_tailscale" >> "${GITHUB_OUTPUT}"
      fi

  - name: Build `sing-box Stable` core
    run: go build -v -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${singbox_stable_VERSION}' -s -w -buildid=" -tags "${{ steps.tags.outputs.build_tags }}" ./cmd/sing-box

  - name: Upload files to workspace
    uses: actions/upload-artifact@v6
    with:
      name: sing-box-stable-${{ matrix.name }}
      path: sing-box*
```

singbox_testing_version:
runs-on: ubuntu-latest
outputs:
singbox_testing_version: ${{ steps.version.outputs.singbox_testing_version }}
singbox_testing_time: ${{ steps.version.outputs.singbox_testing_time }}
singbox_testing_skip_update: ${{ steps.compare.outputs.skip_update }}
steps:
- name: Get `sing-box Testing` version
id: version
run: |
while true; do
releases=$(curl -sSL https://api.github.com/repos/SagerNet/sing-box/releases)
singbox_testing_version=$(echo "${releases}" | jq -r '.[] | select(.tag_name | test("alpha|beta|rc")) | .tag_name' | head -n 1 | sed 's/^v//')
if [[ -n "${singbox_testing_version}" && "${singbox_testing_version}" != "null" ]]; then
singbox_testing_time=$(echo "${releases}" | jq -r '.[] | select(.tag_name | test("alpha|beta|rc")) | (.published_at // .created_at)' | head -n 1 | xargs -I {} date -d '{} +8 hours' '+%Y-%m-%d')
echo "singbox_testing_version=${singbox_testing_version}" >> "${GITHUB_OUTPUT}"
echo "singbox_testing_time=${singbox_testing_time}" >> "${GITHUB_OUTPUT}"
break
fi
echo "未获取到 sing-box Testing 版本号，将在 10 秒后重试..."
sleep 10
done

```
  - name: Compare `sing-box Testing` versions with current release
    id: compare
    run: |
      current_body=$(curl -sSL "https://api.github.com/repos/${{ github.repository }}/releases/tags/sing-box" | jq -r '.body // ""')
      arch="sing-box Testing|${{ steps.version.outputs.singbox_testing_version }}|${{ steps.version.outputs.singbox_testing_time }}"
      IFS="|" read -r name version time <<< "$arch"
      if echo "${current_body}" | grep -q "${name}.*${version}.*${time}"; then
        echo "当前 ${name} 版本已是最新版本 v${version}，无需更新"
        skip_update=true
      else
        echo "当前 ${name} 版本较低，需要更新最新版本至 v${version}"
        skip_update=false
      fi
      echo "skip_update=${skip_update}" >> "${GITHUB_OUTPUT}"
```

singbox_testing_cross:
runs-on: ubuntu-latest
if: ${{ needs.singbox_testing_version.outputs.singbox_testing_skip_update != 'true' }}
strategy:
matrix:
include:
# Linux
- { name: linux-amd64-v1, goos: linux, goarch: amd64, goamd64: v1, variant: purego }
- { name: linux-amd64-v3, goos: linux, goarch: amd64, goamd64: v3, variant: purego }
- { name: linux-armv5, goos: linux, goarch: arm, goarm: 5 }
- { name: linux-armv6, goos: linux, goarch: arm, goarm: 6 }
- { name: linux-armv7, goos: linux, goarch: arm, goarm: 7 }
- { name: linux-arm64, goos: linux, goarch: arm64, variant: purego }
- { name: linux-mips-softfloat, goos: linux, goarch: mips, gomips: softfloat }
- { name: linux-mipsle-softfloat, goos: linux, goarch: mipsle, gomips: softfloat }
- { name: linux-mipsle-hardfloat, goos: linux, goarch: mipsle, gomips: hardfloat }

```
      # Windows
      - { name: windows-amd64-v1, goos: windows, goarch: amd64, goamd64: v1 }
      - { name: windows-amd64-v3, goos: windows, goarch: amd64, goamd64: v3 }
      - { name: windows-arm64, goos: windows, goarch: arm64 }

  fail-fast: false

needs:
  - singbox_testing_version

env:
  GOOS: ${{ matrix.goos }}
  GOARCH: ${{ matrix.goarch }}
  GOAMD64: ${{ matrix.goamd64 }}
  GOARM: ${{ matrix.goarm }}
  GOMIPS: ${{ matrix.gomips }}
  CGO_ENABLED: 0
  singbox_testing_VERSION: ${{ needs.singbox_testing_version.outputs.singbox_testing_version }}

steps:
  - name: Checkout `SagerNet/sing-box`
    uses: actions/checkout@v7
    with:
      repository: SagerNet/sing-box
      ref: testing

  - name: Get `Go` version
    id: go
    run: |
      echo "go_version=$(curl -sSL https://raw.githubusercontent.com/SagerNet/sing-box/testing/.github/workflows/build.yml | grep 'go-version:' | head -n 1 | awk '{print $2}')" >> "${GITHUB_OUTPUT}"

  - name: Setup `Go`
    uses: actions/setup-go@v7
    with:
      go-version: ${{ steps.go.outputs.go_version }}

  - name: Set `build tags`
    id: tags
    run: |
      if [[ "${{ matrix.goos }}" == "linux" ]]; then
        echo "build_tags=with_quic,with_utls,with_clash_api" >> "${GITHUB_OUTPUT}"
      elif [[ "${{ matrix.goos }}" == "windows" ]]; then
        echo "build_tags=with_gvisor,with_quic,with_utls,with_clash_api,with_tailscale" >> "${GITHUB_OUTPUT}"
      fi

  - name: Build `sing-box Testing` core
    run: go build -v -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${singbox_testing_VERSION}' -s -w -buildid=" -tags "${{ steps.tags.outputs.build_tags }}" ./cmd/sing-box

  - name: Upload files to workspace
    uses: actions/upload-artifact@v6
    with:
      name: sing-box-testing-${{ matrix.name }}
      path: sing-box*
```

push_sing-box:
runs-on: ubuntu-latest
if: always()

```
needs:
  - ref1nd_stable_version
  - ref1nd_stable_cross
  - ref1nd_testing_version
  - ref1nd_testing_cross
  - singbox_stable_version
  - singbox_stable_cross
  - singbox_testing_version
  - singbox_testing_cross

env:
  ref1nd_stable_VERSION: ${{ needs.ref1nd_stable_version.outputs.ref1nd_stable_version }}
  ref1nd_stable_TIME: ${{ needs.ref1nd_stable_version.outputs.ref1nd_stable_time }}
  ref1nd_stable_SKIP_UPDATE: ${{ needs.ref1nd_stable_version.outputs.ref1nd_stable_skip_update }}

  ref1nd_testing_VERSION: ${{ needs.ref1nd_testing_version.outputs.ref1nd_testing_version }}
  ref1nd_testing_TIME: ${{ needs.ref1nd_testing_version.outputs.ref1nd_testing_time }}
  ref1nd_testing_SKIP_UPDATE: ${{ needs.ref1nd_testing_version.outputs.ref1nd_testing_skip_update }}

  singbox_stable_VERSION: ${{ needs.singbox_stable_version.outputs.singbox_stable_version }}
  singbox_stable_TIME: ${{ needs.singbox_stable_version.outputs.singbox_stable_time }}
  singbox_stable_SKIP_UPDATE: ${{ needs.singbox_stable_version.outputs.singbox_stable_skip_update }}

  singbox_testing_VERSION: ${{ needs.singbox_testing_version.outputs.singbox_testing_version }}
  singbox_testing_TIME: ${{ needs.singbox_testing_version.outputs.singbox_testing_time }}
  singbox_testing_SKIP_UPDATE: ${{ needs.singbox_testing_version.outputs.singbox_testing_skip_update }}

steps:
  - name: Clone Repository
    uses: actions/checkout@v7

  - name: Download files from workspace
    if: ${{ env.ref1nd_stable_SKIP_UPDATE != 'true' || env.ref1nd_testing_SKIP_UPDATE != 'true' || env.singbox_stable_SKIP_UPDATE != 'true' || env.singbox_testing_SKIP_UPDATE != 'true' }}
    uses: actions/download-artifact@v8
    with:
      path: ./tmp/

  - name: Download `sing-box reF1nd-Stable` files
    if: ${{ env.ref1nd_stable_SKIP_UPDATE != 'true' }}
    run: |
      # Linux - gzip
      mkdir -p ./sing-box/
      linux_archs=(amd64-v1 amd64-v3 armv5 armv6 armv7 arm64 mips-softfloat mipsle-softfloat mipsle-hardfloat)

      for i in "${!linux_archs[@]}"; do
        gzip -n -9 -c "./tmp/sing-box-ref1nd-stable-linux-${linux_archs[i]}/sing-box" > "./sing-box/sing-box-ref1nd-stable-linux-${linux_archs[i]}.gz"
      done

      # Windows
      windows_archs=(amd64-v1 amd64-v3 arm64)

      for j in "${!windows_archs[@]}"; do
        mv -f "./tmp/sing-box-ref1nd-stable-windows-${windows_archs[j]}/sing-box.exe" "./sing-box/sing-box-ref1nd-stable-windows-${windows_archs[j]}.exe"
      done

  - name: Download `sing-box reF1nd-Testing` files
    if: ${{ env.ref1nd_testing_SKIP_UPDATE != 'true' }}
    run: |
      # Linux - gzip
      mkdir -p ./sing-box/
      linux_archs=(amd64-v1 amd64-v3 armv5 armv6 armv7 arm64 mips-softfloat mipsle-softfloat mipsle-hardfloat)

      for i in "${!linux_archs[@]}"; do
        gzip -n -9 -c "./tmp/sing-box-ref1nd-testing-linux-${linux_archs[i]}/sing-box" > "./sing-box/sing-box-ref1nd-testing-linux-${linux_archs[i]}.gz"
      done

      # Windows
      windows_archs=(amd64-v1 amd64-v3 armv5 armv6 armv7 arm64)

      windows_archs=(amd64-v1 amd64-v3 arm64)
      for j in "${!windows_archs[@]}"; do
        mv -f "./tmp/sing-box-ref1nd-testing-windows-${windows_archs[j]}/sing-box.exe" "./sing-box/sing-box-ref1nd-testing-windows-${windows_archs[j]}.exe"
      done

  - name: Download `sing-box Stable` files
    if: ${{ env.singbox_stable_SKIP_UPDATE != 'true' }}
    run: |
      # Linux - gzip
      mkdir -p ./sing-box/
      linux_archs=(amd64-v1 amd64-v3 armv5 armv6 armv7 arm64 mips-softfloat mipsle-softfloat mipsle-hardfloat)

      for i in "${!linux_archs[@]}"; do
        gzip -n -9 -c "./tmp/sing-box-stable-linux-${linux_archs[i]}/sing-box" > "./sing-box/sing-box-stable-linux-${linux_archs[i]}.gz"
      done

      # Windows
      windows_archs=(amd64-v1 amd64-v3 arm64)
      for j in "${!windows_archs[@]}"; do
        mv -f "./tmp/sing-box-stable-windows-${windows_archs[j]}/sing-box.exe" "./sing-box/sing-box-stable-windows-${windows_archs[j]}.exe"
      done

  - name: Download `sing-box Testing` files
    if: ${{ env.singbox_testing_SKIP_UPDATE != 'true' }}
    run: |
      # Linux - gzip
      mkdir -p ./sing-box/
      linux_archs=(amd64-v1 amd64-v3 armv5 armv6 armv7 arm64 mips-softfloat mipsle-softfloat mipsle-hardfloat)

      for i in "${!linux_archs[@]}"; do
        gzip -n -9 -c "./tmp/sing-box-testing-linux-${linux_archs[i]}/sing-box" > "./sing-box/sing-box-testing-linux-${linux_archs[i]}.gz"
      done

      # Windows
      windows_archs=(amd64-v1 amd64-v3 arm64)
      for j in "${!windows_archs[@]}"; do
        mv -f "./tmp/sing-box-testing-windows-${windows_archs[j]}/sing-box.exe" "./sing-box/sing-box-testing-windows-${windows_archs[j]}.exe"
      done

  - name: Check if `sing-box` files exist
    id: check
    run: |
      if ls ./sing-box/* >/dev/null 2>&1; then
        echo "sing-box 文件夹内存在新内核文件，需要上传"
        echo "singbox_exist=true" >> "${GITHUB_OUTPUT}"
      else
        echo "sing-box 文件夹内没有新内核文件，无需上传"
        echo "singbox_exist=false" >> "${GITHUB_OUTPUT}"
      fi

  - name: Remove old UPX assets
    if: ${{ steps.check.outputs.singbox_exist == 'true' }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    run: |
      gh release view sing-box --json assets --jq '.assets[].name' 2>/dev/null | grep '\.upx$' | while IFS= read -r asset; do
        echo "删除旧 UPX 资产: ${asset}"
        gh release delete-asset sing-box "${asset}" --yes
      done || true

  - name: Release and upload `sing-box` assets
    if: ${{ steps.check.outputs.singbox_exist == 'true' }}
    uses: svenstaro/upload-release-action@v2
    with:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
      release_name: sing-box
      tag: sing-box
      overwrite: true
      body: |
        更新 [sing-box reF1nd-Stable 版](https://github.com/reF1nd/sing-box/tree/reF1nd-stable)至 v${{ env.ref1nd_stable_VERSION }}，发布于 ${{ env.ref1nd_stable_TIME }}
        更新 [sing-box reF1nd-Testing 版](https://github.com/reF1nd/sing-box/tree/reF1nd-testing)至 v${{ env.ref1nd_testing_VERSION }}，发布于 ${{ env.ref1nd_testing_TIME }}
        更新 [sing-box Stable 版](https://github.com/SagerNet/sing-box/tree/stable)至 v${{ env.singbox_stable_VERSION }}，发布于 ${{ env.singbox_stable_TIME }}
        更新 [sing-box Testing 版](https://github.com/SagerNet/sing-box/tree/testing)至 v${{ env.singbox_testing_VERSION }}，发布于 ${{ env.singbox_testing_TIME }}
      file_glob: true
      file: ./sing-box/*
```
